### ISSUE TITLE
Node not found. Please check the remote tab is open

### ISSUE THREAD

**Issue by ZoeDeLarge** [bbbscarter/GodotRuntimeDebugTools#2]
"Node not found. Please check the remote tab is open" 
is a message that appears every time I press 3D debugging, and click on the game window, how do I fix it?

**Comment by bbbscarter** [comment]
One of the features of this tool is to synchronise the selected item in the 'remote scene tree' with the running game. However, in order to do that, the remote scene tree needs to be open. 

There are two ways of doing this:
1. Every time you run the game, select the 'Remote' tab in the scene tree.
2. Automate 1 so it happens every time. Go to Editor Settings, and set `debugger/auto_switch_to_remote_scene_tree` to true

I'll add this to the readme. 

Thanks!

**Comment by ZoeDeLarge** [comment]
Thanks!
